### ISSUE TITLE
[Bug] Foreign accents don't work

### ISSUE THREAD

**Issue by Zenrac** [edwardslabs/cleverwrap.py#2]
If cleverbot have to answer with an accented letter in the message, it will replace the letter by something like that : 
![image](https://cloud.githubusercontent.com/assets/19573589/23128163/27ba4fb6-f77e-11e6-8e85-95870e6626a0.png)

**Comment by edwardslabs** [comment]
Thanks for catching this. I have pushed a fix to github and pypi. You should be able to run `pip install --upgrade cleverwrap.`
