### ISSUE TITLE
problems with cyrillic

### ISSUE THREAD

**Issue by pawnhearts** [edwardslabs/cleverwrap.py#6]
Hi! When I write something in Russian to the bot like "привет" and it replies in Russian I get
`UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)`
Old cleverbot package could work just fine with non-latin alphabets.
Thank you.

**Comment by pawnhearts** [comment]
Okay if I remove `.encode('latin-1').decode('utf-8')` on line 85 it  works properly. Why did you put it there in the first place? What's the semantics of that?

http://imgur.com/a/1xbMm

**Comment by edwardslabs** [comment]
Previously it did not work without that line see #2. Thanks for checking sorry it took so long for me to get back to you. I will push an update to pip tomorrow.
