### ISSUE TITLE
Doesn't respond to Japanese characters correctly

### ISSUE THREAD

**Issue by euanworkman** [edwardslabs/cleverwrap.py#9]
Cleverbot, when used through the web interface, responds to Japanese text with a message made in Japanese. When used through this library, however, Cleverbot responds in English, leading me to believe that the message is not getting sent correctly.
```python
from cleverwrap import CleverWrap
cw = CleverWrap("token")
print(cw.say("こにちわ? なまいわ"))
```
Results in Cleverbot responding with an english phrase such as "Oh... Hi John!"

**Comment by edwardslabs** [comment]
Should be fixed now. I updated pypi you just need to update to version cleverwrap-0.2.3.3

**Comment by edwardslabs** [comment]
Example:
```
>>> from cleverwrap import CleverWrap
>>> cb = CleverWrap("token")
>>> cb.say("こにちわ? なまいわ")
'ええ？'
```
